/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimeCard: typeof import('./src/components/AnimeCard.vue')['default']
    AnimeCardGrid: typeof import('./src/components/AnimeCardGrid.vue')['default']
    AnimeCardItem: typeof import('./src/components/AnimeCardItem.vue')['default']
    AnimeCardList: typeof import('./src/components/AnimeCardList.vue')['default']
    AnimeFilter: typeof import('./src/components/AnimeFilter.vue')['default']
    AnimeHeader: typeof import('./src/components/AnimeHeader.vue')['default']
    AnimeRankingList: typeof import('./src/components/AnimeRankingList.vue')['default']
    copy: typeof import('./src/components/AnimeCard copy.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GridPagination: typeof import('./src/components/GridPagination.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    MobileHeader: typeof import('./src/components/MobileHeader.vue')['default']
    OptimizedImage: typeof import('./src/components/OptimizedImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SemanticLayout: typeof import('./src/components/SemanticLayout.vue')['default']
    SimpleCard: typeof import('./src/components/examples/SimpleCard.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList.vue')['default']
    WeekItem: typeof import('./src/components/WeekItem.vue')['default']
  }
}
